config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to:"toppages#index"
  
  get "login", to: "session#new"
  post "login", to: "session#create"
  delete "logout", to: "session#destroy"
  
  get "signup", to: "users#new"

  resources :users, only: [:show, :new, :create]
  resources :circuits, only: [:show]
  resources :reviews, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/circuit.rb
class Circuit < ApplicationRecord
    has_many :reviews
    has_many :reviewer, through: :reviews, source: :user
    
end

app/models/review.rb
class Review < ApplicationRecord
    validates :content, presence: true, length: { maximum: 255 }
    
    belongs_to :user
    belongs_to :circuit
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, presence: true, length: { maximum: 255 }, uniqueness: { case_sensitive: false }
    
    has_secure_password
    
    has_many :reviews
    has_many :reviewings, through: :reviews, source: :circuit
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
  include SessionsHelper
    
  private
    
  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  
end

app/controllers/circuits_controller.rb
class CircuitsController < ApplicationController

  def show
    if logged_in?
      @review = current_user.reviews.build
    end
    
    @circuit = Circuit.find(params[:id])
    @reviews = @circuit.reviews.order(created_at: :desc).page(params[:page]).per(5)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :require_user_logged_in 
  before_action :correct_user, only: [:destroy]
  
  def create
    @review = current_user.reviews.build(review_params)
    @review.circuit_id = params[:circuit_id]
    if @review.save
      flash[:success] = "コメントを投稿しました"
      redirect_back(fallback_location: root_path)
    else
      flash.now[:danger] = "投稿に失敗しました"
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    @review.destroy
    flash[:success] = "メッセージを削除しました"
    redirect_back(fallback_location: root_path)
  end
  
  private
  
  def review_params
    params.require(:review).permit(:content, :circuit_id)
  end
  
  def correct_user
    @review = current_user.reviews.find_by(id: params[:id])
    unless @review
      redirect_to root_url
    end
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    name = params[:session][:name]
    password = params[:session][:password]
    if login(name, password)
      flash[:success] = "ログインに成功しました"
      redirect_to @user
    else
      flash.now[:danger] = "ログインに失敗しました"
      render :"new"
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "ログアウトしました"
    redirect_to root_url
  end
  
  private
  
  def login(name, password)
    @user = User.find_by(name: name)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    @circuits1 = Circuit.where(region: "北海道・東北")
    @circuits2 = Circuit.where(region: "関東")
    @circuits3 = Circuit.where(region: "中部")
    @circuits4 = Circuit.where(region: "近畿")
    @circuits5 = Circuit.where(region: "中国・四国")
    @circuits6 = Circuit.where(region: "九州")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    require_user_logged_in
    @user = User.find(params[:id])
    @reviews = @user.reviews.order(created_at: :desc).page(params[:page]).per(5)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = "ユーザを登録しました"
      redirect_to @user
    else
      flash.now[:danger] = "ユーザの登録に失敗しました"
      render :new
    end
  end
  
  def edit
  end
  
  def update
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
    
  def logged_in?
    !!current_user
  end
end

app/views/circuits/show.html.erb
<div class="circuit-container">
<h1 class="p-3"><%= @circuit.circuit %></h1>
<div class="circuit-wrapper">
  <img class="col-6 circuit-img" src="<%= @circuit.img %>" alt="<%= @circuit.circuit %>">
  <div class="circuit-list">
    <ul class="list-unstyled p-4">
      <b>コース情報</b>
      <li>場所：<%= @circuit.root %></li>
      <li>コース：<%= @circuit.course %></li>
      <li>コースタイプ：<%= @circuit.course_type %></li>
      <li>公式サイト：<%= link_to @circuit.circuit, @circuit.site_link %></li>
    </ul>
  </div>
</div>
<h2 class="mt-5 pt-5 pb-4"><%= @circuit.circuit %>の口コミ</h2>
  <div class="offset-sm-1 col-sm-10 content-container">
    <%= render 'reviews/reviews', reviews: @reviews %>
  </div>
</div>
  <% if logged_in? %>
    <div class="row">
      <aside class="offset-sm-3 col-sm-6 pb-5">
        <%= form_with(model: current_user.reviews.build, local: true) do |f| %>
        <%= render "layouts/error_messages", model: f.object %>
          <div>
            <%= f.text_area :content, class: 'form-control', rows: 5 %>
            <%= hidden_field_tag :circuit_id, @circuit.id %>
          </div>
          <%= f.submit '投稿', class: 'btn btn-primary btn-block' %>
        <% end %>
      </aside>
    </div>
  </div>
<% end %>
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
  

app/views/layouts/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
    <p>© 2019 CircuitReviews</p>
</footer>

app/views/layouts/_navbar.html.erb
<header class="header-container">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <%= link_to "Circuit Reviews", root_url, class: "navbar-brand logo", data: {turbolinks: false} %>
      <button class="navbar-toggler" type="button" data-toggler="collapse" data-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>
        
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-out"></ul>
        <ul class="navbar-nav">
            <li class="nav-item"></li>
            <li class="nav-item dropdown">
              <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">地域</a>
              <ul class="dropdown-menu dropdown-menu-right">
                <li class="dropdown-item"><a href="/#chapter1">北海道・東北</a></li>
                <li class="dropdown-item"><a href="/#chapter2">関東</a></li>
                <li class="dropdown-item"><a href="/#chapter3">中部</a></li>
                <li class="dropdown-item"><a href="/#chapter4">近畿</a></li>
                <li class="dropdown-item"><a href="/#chapter5">中国・四国</a></li>
                <li class="dropdown-item"><a href="/#chapter6">九州</a></li>
              </ul>
            </li>
            <% if logged_in? %>
              <li class="navbar-item"><%= link_to current_user.name, user_path(current_user), class: "nav-link" %></li>
              <li class="navbar-item"><%= link_to "ログアウト", logout_path, method: :delete, class: "nav-link" %></li>
            <% else %>
              <li class="navbar-item"><%= link_to "新規登録", signup_path, class: "nav-link" %></li>
              <li class="navbar-item"><%= link_to "ログイン", login_path, class: "nav-link" %></li>
            <% end %>
        </ul>
      </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>CircuitReviews</title>
    <meta name="description" content="日本全国のサーキットレビューサイト。">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body>
    <%= render "layouts/navbar" %>
    
    <div class="wrapper">
      <%= render "layouts/flash_message" %>
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/reviews/_reviews.html.erb
<ul class="list-unstyled">
  <% reviews.each do |review| %>
    <li class="media mb-3">
      <div class="media-body">
        <div class="review-container">
          <h4 class="m-0"><%= review.user.name %></h4>
          <p class="reviews-created"><%= review.created_at %></p>
          <h5 class="p-2 coment-container"><%= review.content %></h5>
        </div>
        <div class="pl-2">
          <% if current_user == review.user %>
            <%= link_to "削除", review, method: :delete, class: "btn btn-danger btn-sm" %>
          <% end %>
        </div>
      </div>
    </li>
  <% end %>
  <%= paginate @reviews %>
</ul>

app/views/reviews/_user_reviews.html.erb
<ul class="list-unstyled">
  <% reviews.each do |review| %>
    <li class="media mb-3">
      <div class="media-body">
        <div class="review-container">
          <h4 class="m-0"><%= link_to review.circuit.circuit, review.circuit %></h4>
          <p class="reviews-created"><%= review.created_at %></p>
          <h5 class="p-2" class="coment-container"><%= review.content %></h5>
        </div>
        <div>
          <% if current_user == review.user %>
            <%= link_to "削除", review, method: :delete, data: { confirm: "You sure?" }, class: "btn btn-danger btn-sm" %>
          <% end %>
        </div>
      </div>
    </li>
  <% end %>
  <%= paginate @reviews %>
</ul>

app/views/session/new.html.erb
<div class="text-center">
  <h1>ログイン</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(url: login_path, scope: :session, local: true) do |f| %>

      <div class="form-group">
        <%= f.label :name, 'ユーザ名' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <%= f.submit 'ログイン', class: 'btn btn-primary btn-block' %>
    <% end %>

    <p>ユーザ登録しましたか? <%= link_to 'Sign up now!', signup_path %></p>
  </div>
</div>

app/views/toppages/index.html.erb
<div class="toppage-container">
  <div class="toppage-img">
    <div class="slides">
      <img class="slide" src="http://www.wallpaper-box.com/car/images/car60.jpg" alt="トップページの画像">
      <img class="slide" src="http://carchandaisuki.com/wp/wp-content/uploads/2018/08/p11.jpg" alt="トップページの画像">
      <img class="slide" src="https://cdn.snsimg.carview.co.jp/minkara/userstorage/000/023/811/350/3d8906568a.jpg?ct=f6ad9ba8d0ec" alt="トップページの画像">
      <img class="slide" src="https://images.pexels.com/photos/395222/pexels-photo-395222.jpeg?cs=srgb&dl=208-395222.jpg&fm=jpg" alt="トップページの画像">
      <img class="slide" src="http://st.gde-fon.com/wallpapers_original/559990_wrc_2001_mitsubishi_lancer_1617x1080_www.Gde-Fon.com.jpg">
    </div>
    <h1>Circuit Reviews</h1>
  </div>
  <div class="region-container">
    <h2 class="p-3 mt-5">地域別サーキット一覧</h2>
    <ul class="region m-0">
      <div class="circuit-list">
        <h3 id="chapter1">北海道・東北</h3>
        <% @circuits1.each do |circuit| %>
          <li><%= link_to circuit.circuit, circuit_path(circuit) %></li>
        <% end %>
      </div>
      <div class="circuit-list">  
        <h3 id="chapter2">関東</h3>
        <% @circuits2.each do |circuit| %>
          <li><%= link_to circuit.circuit, circuit_path(circuit) %></li>
        <% end %>
      </div>
      <div class="circuit-list">
        <h3 id="chapter3">中部</h3>
        <% @circuits3.each do |circuit| %>
          <li><%= link_to circuit.circuit, circuit_path(circuit) %></li>
        <% end %>
      </div>
      <div class="circuit-list">
        <h3 id="chapter4">近畿</h3>
        <% @circuits4.each do |circuit| %>
          <li><%= link_to circuit.circuit, circuit_path(circuit) %></li>
        <% end %>
      </div>
      <div class="circuit-list">
        <h3 id="chapter5">中国・四国</h3>
        <% @circuits5.each do |circuit| %>
          <li><%= link_to circuit.circuit, circuit_path(circuit) %></li>
        <% end %>
      </div>
      <div class="circuit-list">
        <h3 id="chapter6">九州</h3>
        <% @circuits6.each do |circuit| %>
          <li><%= link_to circuit.circuit, circuit_path(circuit) %></li>
        <% end %>
      </div>
    </ul>
  </div>
</div>

app/views/users/_user_reviews.html.erb
<ul class="list-unstyled">
  <% reviews.each do |review| %>
    <li class="media mb-3">
      <div class="offset-sm-2 media-body">
        <div class="col-sm-10 review-container">
          <h4 class="m-0"><%= link_to review.circuit.circuit, review.circuit %></h4>
          <p class="reviews-created"><%= review.created_at %></p>
          <h5 class="p-2 coment-container"><%= review.content %></h5>
        </div>
        <div class="pl-2">
          <% if current_user == review.user %>
            <%= link_to "削除", review, method: :delete, class: "btn btn-danger btn-sm" %>
          <% end %>
        </div>
      </div>
    </li>
  <% end %>
  <%= paginate @reviews %>
</ul>

app/views/users/new.html.erb
<div class="text-center">
  <h1>新規登録</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
    
      <%= render "layouts/error_messages", model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, 'ユーザ名' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'パスワード確認' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit '入力完了', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-container pt-4">
    <h1>マイページ</h1>
    <P class="p-3">ユーザ名：<b><%= @user.name %></b></p>
    <h2>投稿したレビュー</h2>
</div>
<%= render "users/user_reviews", reviews: @user.reviews %>